package com.f.patch.constant;

public enum PatchEvent {
    BEFORE_LOAD_PROPERTY,AFTER_LOAD_PROPERTY,
    BEFORE_LOAD_FILE,AFTER_LOAD_FILE,
    BEFORE_COMPARE,ARTER_COMPARE,
    BEFORE_EXPORT,AFTER_EXPORT
}
